### ISSUE TITLE
Performance comparison with Julia original code?

### ISSUE THREAD

**Issue by paugier** [ElofssonLab/pyGaussDCA#1]
Hi,

I see that pyGaussDCA uses Pythran and that it was translated from a Julia code.

Did you measure how GaussDCA.jl and pyGaussDCA compare in terms of performance?

It is much slower?

**Comment by arneelof** [comment]
It should be faster by a factor of 2 or more (but not so important as even
the Julia implementation is fast enough).

See..

https://www.biorxiv.org/content/early/2018/08/02/383133.full.pdf+html

**Comment by paugier** [comment]
Thank you for your reply and congratulation for this work. It's very good news that a 100% Python code can reach such performance! I may suggest that you add some words on this fact in the README. People tend to think that Julia is much faster than Python so my question make sense when one reads *"It is based on the original code in Julia. What is different? It is written as a Python library to be more easily integrated with our software."*

**Comment by Dapid** [comment]
That is a good idea, I have added a few lines.
